spring.profiles.active=local

# 1. Database Connection Settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect